# Use new trusty images, should yield newer compilers and packages
dist: trusty
sudo: required
language: cpp

matrix:
include:
- os: linux
	addons:
	apt:
		sources:
		- ubuntu-toolchain-r-test
		packages:
		- gcc-5
		- g++-5
	env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

     
before_install:
	eval "$(MATRIX_EVAL)"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autotools-dev
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y autoconf-archive
  - sudo autoreconf --install --force
script:
  - mkdir build
  - cd build
  - ../configure 
  - make